name: 'SSH key multi-line'
description: 'Converts multi-line SSH Key into single line.'
inputs:
  ENVIRONMENT:  # id of input
    description: 'The environment to be build.'
    required: false
  SSH-KEY-DEV:  # id of input
    description: 'SSH Key to transform from multi to single line.'
    required: true
  SSH-KEY-TEST:  # id of input
    description: 'SSH Key to transform from multi to single line.'
    required: true
  SSH-KEY-STAGE:  # id of input
    description: 'SSH Key to transform from multi to single line.'
    required: true
  SSH-KEY-PROD:  # id of input
    description: 'SSH Key to transform from multi to single line.'
    required: true
  BASTION-IP-DEV:  # id of input
    description: 'The IP of the DEV Bastion host'
    required: false
  BASTION-IP-TEST:  # id of input
    description: 'The IP of the TEST Bastion host'
    required: false
  BASTION-IP-STAGE:  # id of input
    description: 'The IP of the STAGE Bastion host'
    required: false
  BASTION-IP-PROD:  # id of input
    description: 'The IP of the PROD Bastion host'
    required: false
  SG-ID-DEV:  # id of input
    description: 'The ID of the DEV Bastion host SSH security group'
    required: false
  SG-ID-TEST:  # id of input
    description: 'The ID of the TEST Bastion host SSH security group'
    required: false
  SG-ID-STAGE:  # id of input
    description: 'The ID of the STAGE Bastion host SSH security group'
    required: false
  SG-ID-PROD:  # id of input
    description: 'The ID of the PROD Bastion host SSH security group'
    required: false
  REGION-DEV:  # id of input
    description: 'The region for the development resources'
    required: false
  REGION-TEST:  # id of input
    description: 'The region for the testing resources'
    required: false
  REGION-STAGE:  # id of input
    description: 'The region for the staging resources'
    required: false
  REGION-PROD:  # id of input
    description: 'The region for the production resources'
    required: false
  SG-SCRIPT-URL-DEV:  # id of input
    description: 'The URL of the dev casino SG'
    required: false
  SG-SCRIPT-URL-TEST:  # id of input
    description: 'The URL of the testing casino SG'
    required: false
  SG-SCRIPT-URL-PROD:  # id of input
    description: 'The URL of the production casino SG'
    required: false
  AWS-BUCKET-KYC-DEV:  # id of input
    description: 'The S3 bucket KYC dev'
    required: false
  AWS-BUCKET-KYC-TEST:  # id of input
    description: 'The S3 bucket KYC testing'
    required: false
  AWS-BUCKET-KYC-STAGE:  # id of input
    description: 'The S3 bucket KYC staging'
    required: false
  AWS-BUCKET-KYC-PROD:  # id of input
    description: 'The S3 bucket KYC production'
    required: false
  S3-BUCKET-DEV:  # id of input
    description: 'The S3 bucket Strapi dev'
    required: false
  S3-BUCKET-TEST:  # id of input
    description: 'The S3 bucket Strapi testing'
    required: false
  S3-BUCKET-STAGE:  # id of input
    description: 'The S3 bucket Strapi staging'
    required: false
  S3-BUCKET-PROD:  # id of input
    description: 'The S3 bucket Strapi production'
    required: false
  DB-ADDR-DEV:  # id of input
    description: 'The DB dev address'
    required: false
  DB-ADDR-TEST:  # id of input
    description: 'The DB testing address'
    required: false
  DB-ADDR-STAGE:  # id of input
    description: 'The DB staging address'
    required: false
  DB-ADDR-PROD:  # id of input
    description: 'The DB production address'
    required: false
  SOFTSWISS-MP-REST-URL-DEV:  # id of input
    description: 'The Softswiss dev address'
    required: false
  SOFTSWISS-MP-REST-URL-TEST:  # id of input
    description: 'The Softswiss testing address'
    required: false
  SOFTSWISS-MP-REST-URL-PROD:  # id of input
    description: 'The Softswiss production address'
    required: false
  KAFKA-BOOTSTRAP-SERVERS-DEV:  # id of input
    description: 'The DB dev address'
    required: false
  KAFKA-BOOTSTRAP-SERVERS-TEST:  # id of input
    description: 'The DB testing address'
    required: false
  KAFKA-BOOTSTRAP-SERVERS-STAGE:  # id of input
    description: 'The DB staging address'
    required: false
  KAFKA-BOOTSTRAP-SERVERS-PROD:  # id of input
    description: 'The DB production address'
    required: false
  CUSTOMER-IO-TRACK-DEV:  # id of input
    description: 'The dev API url for customer IO'
    required: false
  CUSTOMER-IO-TRACK-TEST:  # id of input
    description: 'The test API url for customer IO'
    required: false
  CUSTOMER-IO-TRACK-PROD:  # id of input
    description: 'The prod API url for customer IO'
    required: false
outputs:
  SSH-KEY-SINGLE:
    description: "Single line SSH key"
    value: ${{ steps.environment_check.outputs.KEY }}
  ENV_BRANCH:
    description: "The branch tag to be applied"
    value: ${{ steps.environment_check.outputs.ENV_BRANCH }}
  ENV_REGION:
    description: "The region to create the resources in"
    value: ${{ steps.environment_check.outputs.ENV_REGION }}
  BASTION_IP:
    description: "The IP of the Bastion host"
    value: ${{ steps.environment_check.outputs.BASTION_IP }}
  SG_ID:
    description: "The ID of the Bastion host SSH security group"
    value: ${{ steps.environment_check.outputs.SG_ID }}
  KAFKA-BOOTSTRAP-SERVERS:
    description: "The DB production address"
    value: ${{ steps.environment_check.outputs.KAFKA-BOOTSTRAP-SERVERS }}
  SOFTSWISS-MP-REST-URL:
    description: "The Softswiss address"
    value: ${{ steps.environment_check.outputs.SOFTSWISS-MP-REST-URL }}
  DB-ADDR:
    description: "The DB address"
    value: ${{ steps.environment_check.outputs.DB-ADDR }}
  S3-BUCKET:
    description: "The S3 bucket for Strapi"
    value: ${{ steps.environment_check.outputs.S3-BUCKET }}
  AWS-BUCKET-KYC:
    description: "The S3 KYC bucket"
    value: ${{ steps.environment_check.outputs.AWS-BUCKET-KYC }}
  SG-SCRIPT-URL:
    description: "The URL of the casino SG"
    value: ${{ steps.environment_check.outputs.SG-SCRIPT-URL }}
  CUSTOMER-IO-TRACK:
    description: "The API url for customer IO"
    value: ${{ steps.environment_check.outputs.CUSTOMER_IO_TRACK }}
runs:
  using: "composite"
  steps:
    - name: Check if ENVIRONMENT variable is present
      id: env_check
      run: |
        if [ "${{ inputs.ENVIRONMENT }}" == "testing" ]; then
          present="true"
          echo "::set-output name=present::true"
        elif [ "${{ inputs.ENVIRONMENT }}" == "production" ]; then
          present="true"
          echo "::set-output name=present::true"
        elif [ "${{ inputs.ENVIRONMENT }}" == "staging" ]; then
          present="true"
          echo "::set-output name=present::true"
        elif [ "${{ inputs.ENVIRONMENT }}" == "development" ]; then
          present="true"
          echo "::set-output name=present::true"
        else
          present="false"
          echo "::set-output name=present::false"
        fi
      shell: bash
    - name: Set environment variables
      id: environment_check
      run: |
        if [ "${{ inputs.ENVIRONMENT }}" == "testing" ] && ([ "${{ github.ref }}" == refs/heads/master ] || [ "${{ github.ref }}" == refs/heads/main ]); then
           multi_line="${{ inputs.SSH-KEY-TEST }}"
           multi_line="${multi_line//$'\n'/'%0A'}"
           multi_line="${multi_line//$'\r'/'%0D'}"
           echo "::set-output name=KEY::$multi_line"
        elif [ "${{ inputs.ENVIRONMENT }}" == "production" ] && ([ "${{ github.ref }}" == refs/heads/master ] || [ "${{ github.ref }}" == refs/heads/main ]); then
           multi_line="${{ inputs.SSH-KEY-PROD }}"
           multi_line="${multi_line//$'\n'/'%0A'}"
           multi_line="${multi_line//$'\r'/'%0D'}"
           echo "::set-output name=KEY::$multi_line"
        elif [ "${{ inputs.ENVIRONMENT }}" == "staging" ] && ([ "${{ github.ref }}" == refs/heads/master ] || [ "${{ github.ref }}" == refs/heads/main ]); then
           multi_line="${{ inputs.SSH-KEY-STAGE }}"
           multi_line="${multi_line//$'\n'/'%0A'}"
           multi_line="${multi_line//$'\r'/'%0D'}"
           echo "::set-output name=KEY::$multi_line"
        elif [ "${{ inputs.ENVIRONMENT }}" == "development" ] && ([ "${{ github.ref }}" == refs/heads/master ] || [ "${{ github.ref }}" == refs/heads/main ]); then
           multi_line="${{ inputs.SSH-KEY-DEV }}"
           multi_line="${multi_line//$'\n'/'%0A'}"
           multi_line="${multi_line//$'\r'/'%0D'}"
           echo "::set-output name=KEY::$multi_line"
        fi
        if [ "${{ github.ref }}" == "refs/heads/stage" ] && [ "${{ steps.env_check.outputs.present }}" == "false" ]; then
           echo "::set-output name=ENV_BRANCH::stage"
           echo "::set-output name=ENV_REGION::${{ inputs.REGION-STAGE }}"
           echo "::set-output name=BASTION_IP::${{ inputs.BASTION-IP-STAGE }}"
           echo "::set-output name=SG_ID::${{ inputs.SG-ID-TEST }}"
           echo "::set-output name=SG-SCRIPT-URL::${{ inputs.SG-SCRIPT-URL-TEST }}"
           echo "::set-output name=AWS-BUCKET-KYC::${{ inputs.AWS-BUCKET-KYC-STAGE }}"
           echo "::set-output name=S3-BUCKET::${{ inputs.S3-BUCKET-STAGE }}"
           echo "::set-output name=DB-ADDR::${{ inputs.DB-ADDR-STAGE }}"
           echo "::set-output name=SOFTSWISS-MP-REST-URL::${{ inputs.SOFTSWISS-MP-REST-URL-TEST }}"
           echo "::set-output name=KAFKA-BOOTSTRAP-SERVERS::${{ inputs.KAFKA-BOOTSTRAP-SERVERS-STAGE }}"
           echo "::set-output name=CUSTOMER_IO_TRACK::${{ inputs.CUSTOMER-IO-TRACK-TEST }}"
           multi_line="${{ inputs.SSH-KEY-STAGE }}"
           multi_line="${multi_line//$'\n'/'%0A'}"
           multi_line="${multi_line//$'\r'/'%0D'}"
           echo "::set-output name=KEY::$multi_line"
        elif [ "${{ github.ref }}" == "refs/heads/testing" ] && [ "${{ steps.env_check.outputs.present }}" == "false" ]; then
           echo "::set-output name=ENV_BRANCH::test"
           echo "::set-output name=ENV_REGION::${{ inputs.REGION-TEST }}"
           echo "::set-output name=BASTION_IP::${{ inputs.BASTION-IP-TEST }}"
           echo "::set-output name=SG_ID::${{ inputs.SG-ID-TEST }}"
           echo "::set-output name=SG-SCRIPT-URL::${{ inputs.SG-SCRIPT-URL-TEST }}"
           echo "::set-output name=AWS-BUCKET-KYC::${{ inputs.AWS-BUCKET-KYC-TEST }}"
           echo "::set-output name=S3-BUCKET::${{ inputs.S3-BUCKET-TEST }}"
           echo "::set-output name=DB-ADDR::${{ inputs.DB-ADDR-TEST }}"
           echo "::set-output name=SOFTSWISS-MP-REST-URL::${{ inputs.SOFTSWISS-MP-REST-URL-TEST }}"
           echo "::set-output name=KAFKA-BOOTSTRAP-SERVERS::${{ inputs.KAFKA-BOOTSTRAP-SERVERS-TEST }}"
           echo "::set-output name=CUSTOMER_IO_TRACK::${{ inputs.CUSTOMER-IO-TRACK-TEST }}"
           multi_line="${{ inputs.SSH-KEY-TEST }}"
           multi_line="${multi_line//$'\n'/'%0A'}"
           multi_line="${multi_line//$'\r'/'%0D'}"
           echo "::set-output name=KEY::$multi_line"
        elif [ "${{ github.ref }}" == "refs/heads/production" ] && [ "${{ steps.env_check.outputs.present }}" == "false" ]; then
           echo "::set-output name=ENV_BRANCH::prod"
           echo "::set-output name=ENV_REGION::${{ inputs.REGION-PROD }}"
           echo "::set-output name=BASTION_IP::${{ inputs.BASTION-IP-PROD }}"
           echo "::set-output name=SG_ID::${{ inputs.SG-ID-PROD }}"
           echo "::set-output name=SG-SCRIPT-URL::${{ inputs.SG-SCRIPT-URL-PROD }}"
           echo "::set-output name=AWS-BUCKET-KYC::${{ inputs.AWS-BUCKET-KYC-PROD }}"
           echo "::set-output name=S3-BUCKET::${{ inputs.S3-BUCKET-PROD }}"
           echo "::set-output name=DB-ADDR::${{ inputs.DB-ADDR-PROD }}"
           echo "::set-output name=SOFTSWISS-MP-REST-URL::${{ inputs.SOFTSWISS-MP-REST-URL-PROD }}"
           echo "::set-output name=KAFKA-BOOTSTRAP-SERVERS::${{ inputs.KAFKA-BOOTSTRAP-SERVERS-PROD }}"
           echo "::set-output name=CUSTOMER_IO_TRACK::${{ inputs.CUSTOMER-IO-TRACK-PROD }}"
           multi_line="${{ inputs.SSH-KEY-PROD }}"
           multi_line="${multi_line//$'\n'/'%0A'}"
           multi_line="${multi_line//$'\r'/'%0D'}"
           echo "::set-output name=KEY::$multi_line"
        elif [ "${{ steps.env_check.outputs.present }}" == "false" ]; then
           echo "::set-output name=ENV_BRANCH::dev"
           echo "::set-output name=ENV_REGION::${{ inputs.REGION-DEV }}"
           echo "::set-output name=BASTION_IP::${{ inputs.BASTION-IP-DEV }}"
           echo "::set-output name=SG_ID::${{ inputs.SG-ID-DEV }}"
           echo "::set-output name=SG-SCRIPT-URL::${{ inputs.SG-SCRIPT-URL-DEV }}"
           echo "::set-output name=AWS-BUCKET-KYC::${{ inputs.AWS-BUCKET-KYC-DEV }}"
           echo "::set-output name=S3-BUCKET::${{ inputs.S3-BUCKET-DEV }}"
           echo "::set-output name=DB-ADDR::${{ inputs.DB-ADDR-DEV }}"
           echo "::set-output name=SOFTSWISS-MP-REST-URL::${{ inputs.SOFTSWISS-MP-REST-URL-DEV }}"
           echo "::set-output name=KAFKA-BOOTSTRAP-SERVERS::${{ inputs.KAFKA-BOOTSTRAP-SERVERS-DEV }}"
           echo "::set-output name=CUSTOMER_IO_TRACK::${{ inputs.CUSTOMER-IO-TRACK-DEV }}"
           multi_line="${{ inputs.SSH-KEY-DEV }}"
           multi_line="${multi_line//$'\n'/'%0A'}"
           multi_line="${multi_line//$'\r'/'%0D'}"
           echo "::set-output name=KEY::$multi_line"
        fi
      shell: bash

